version: '3'
services:
  postgres:
    image: postgres:12.1-alpine
    env_file:
      - .env
    restart: always

  redis:
    image: redis:5.0.7-alpine
    restart: always

  web:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
      - redis
