version: '3'
services:
  postgres:
    image: postgres:12.1-alpine
    env_file:
      - .env

  redis:
    image: redis:5.0.7-alpine

  web:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
